# Generated by Django 5.1.2 on 2024-11-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mtweet", "0005_meep"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
