# Generated by Django 5.1.2 on 2024-11-12 23:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mtweet", "0006_profile_profile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meep",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="meep_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
